version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./static/tables:/app/static/tables
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  static_data: